config/routes.rb
Elie::Application.routes.draw do

  resources :images, only: [:show, :new, :create]

  match "search" => "search#index", :as => :search
  match "/auth/discogs/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "user/profile" => "user#profile"
  match "user/folders" => "user#folders", :as => :folders
  match "user/folder/:folder" => "user#folder"

  root :to => "search#index"

end

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :image
  
  has_attached_file :image, 
    :styles => {
    :large => "900x600>",
    :medium => "600x400>",
    :square => "100x100#", 
    :small => "300x200>" 
  },
  :convert_options => { :all => '-auto-orient' }

  # Validate content type
  validates_attachment_content_type :image, :content_type => /\Aimage/

  # Validate filename
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/]

  # Explicitly do not validate
  do_not_validate_attachment_file_type :image

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid

  def self.create_with_omniauth(auth)

    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["username"]
      user.token = auth["credentials"].token
      user.secret = auth["credentials"].secret
    end
  end

  def update_credentials (auth)
    self.token = auth["credentials"].token
    self.secret = auth["credentials"].secret
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protect_from_forgery
  helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end


  def create
    @image = Image.new(params[:image])

    if @image.save
      redirect_to controller: "search", img_url: @image.image.url(:large).split('?').first
    end 
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  include SearchHelper
  include UserHelper

  def index

    @results = nil
    @name = nil
    @image = Image.new

    unless ( params[:img_url].nil? ) then 

      album_name = google_album_art(params[:img_url]) 

      if album_name.nil? 
        flash.now[:error] = "Did you enter the url for an image?" 
      elsif album_name.empty?  
        flash.now[:error] = "Can't find album name for this"
      else 

        r = search_discogs(album_name)
        @response = JSON.parse(r.body)

        @response['results'].each do | el | 

          uri = URI.parse(el['thumb'])
          resp = user_access_token.get(el['thumb'])

          file_name = 'tmp/' + File.basename(uri.path)
          open( file_name,"wb") { |file|
            file.write(resp.body)
          }

          @image = Image.new(:image => File.open(file_name))

          if @image.save
            el['thumb'] = @image.image.url(:original).split('?').first
          end 
        end 

        # puts JSON.pretty_generate(@response)
 
        @name = album_name
      end 

    end 

  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    auth.to_yaml
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    user.update_credentials(auth)
    session[:user_id] = user.id
    session[:user_token] = user.token 
    session[:user_secret] = user.secret 
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    session[:user_token] = nil
    session[:user_secret] = nil     
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  include UserHelper

  def profile

    json = get_user_response get_folder('awesomeness')

    render :json => json
  end

  def folders
    json = get_user_response user_folders
    @data = json['folders']
  end 

  def folder
    json = get_user_response get_folder params[:folder]
    render :json => json
  end 

  private   
    def user_folders
      "/users/#{current_user.name}/collection/folders"
    end

    def get_folder ( folder )
      json = get_user_response user_folders
      folders = json['folders']
      match = folders.select { |e| e['name'] == folder }.first

      folder_url = match['resource_url']
      folder_url.slice!('http://api.discogs.com')
      folder_url + '/releases'
    end 

    def get_user_response (api_call)
      
      # use the access token as an agent to get the home timeline
      JSON.parse user_access_token.get(api_call).body
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/search_helper.rb
module SearchHelper

	require 'net/http'
	require 'uri'

	DISCOGS_API = "http://api.discogs.com/database/search"

	def search_discogs (term) 
		uri = URI(DISCOGS_API)

		request = Net::HTTP::Get.new(uri.to_s + "?" + query_string(term))
		request.add_field("Accept", "application/json")
		request.add_field("User-Agent", "Recccords")

		Net::HTTP.new(uri.host).start do |http|
			http.request(request)
		end 
	end 

	def query_string ( term ) 
		query = {:q => term, :format => 'vinyl', :type => 'release'}
		URI.escape query.map { |k,v| "#{k}=#{v}" }.join('&')
	end 


  def mechanize_agent
  	@agent ||= Mechanize.new { |agent|
			agent.user_agent_alias = 'Mac Safari'
		}
  end

  GOOLGE_SEARCH_URL = 'http://www.google.co.in/imghp?sbi=1'
  INTERMEDIATE_PAGE_BUTTON = 'search by image'

  def google_album_art (img_url)

  	name = nil

  	# begin 
  		mechanize_agent.get(GOOLGE_SEARCH_URL) do |upload_page|

        # get the form then 
        # get the q name element and fill with img url 
  			upload_form = upload_page.form('f')
  			upload_form.q = img_url

  			intermediate_page = mechanize_agent.submit (upload_form)

        # click on this link 
  			final_page = mechanize_agent.click(intermediate_page.link_with(:text => INTERMEDIATE_PAGE_BUTTON))

        # final_page.save_as 'final.html'
  			name = find_album_name (final_page.body)

  		end
  	# rescue 
  	# 	name = nil
  	# end 

  	name 

  end 

  def find_album_name (html) 
		doc = Nokogiri::HTML(html)

    # find this under div#topstuff > div > div > a 
		names = doc.xpath('//div[@id="topstuff"]/div/div/a').map do | stuff | 
			stuff.content 
		end
    puts names
		names.reject! { |e| e.empty? }
		names.first		
	end 

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper

  def user_access_token 
    
    def prepare_access_token(oauth_token, oauth_token_secret)
      consumer = OAuth::Consumer.new("BCvgSeawxoZCPYqThnPV", "FxEPTHDkhtqGoZGHhrQDojwgyPIEhLGm", { :site => "http://api.discogs.com/" })
      # now create the access token object from passed values
      token_hash = { :oauth_token => oauth_token,
                     :oauth_token_secret => oauth_token_secret }

      access_token = OAuth::AccessToken.from_hash(consumer, token_hash )
      return access_token
    end

    # Exchange our oauth_token and oauth_token secret for the AccessToken instance.
    @access_token ||= prepare_access_token(current_user.token,current_user.secret)

  end 
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<%= form_for @image, :url => images_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :image %>
  <%= form.submit "Submit" %>
<% end %>

app/views/images/show.html.erb
<%= image_tag @image.image.url %>
<div><%= @image.image.url %></div> 
<div><%= @image.image.url(:large).split('?').first %></div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Recccords</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span7">
      <ul class="nav nav-pills">
        <li><%= link_to "Search", search_path %></li> 
        <% if current_user %> 
          <li><%= link_to "Folders", folders_path %></li> 
        <% end %> 
      </ul> 
    </div> 
    <div class="span5">
      <div id="user_nav">
        <% if current_user %>
          Welcome, <%= current_user.name %>!
          <%= link_to "Sign Out", signout_path %>
        <% else %>
          <%= link_to "Sign in with Discogs", "/auth/discogs" %>
        <% end %>
      </div> 
    </div>

  </div> 
	<%= yield %>
</div>

</body>
</html>

app/views/search/index.html.erb
<div class="row">
	<div class="span12">
		<h1>Google + Discogs</h1>
		<% if flash.now[:error] %>
			<div class="error"><%= flash.now[:error] %></div>
		<% end %> 		
		<%= form_tag("/search", :method => "get") do %>
		  <%= text_field_tag(:img_url, nil, { :placeholder => "enter image url and hit enter", :class => "img-input" })%>
		  <%= submit_tag("Search", :class => "hidden") %>
		<% end %>
		<%= form_for @image, :url => images_path, :html => { :multipart => true } do |f| %>
		  <%= f.file_field :image %>
		  <%= f.submit "Submit" %>
		<% end %>		
 	</div>
</div>
<% unless @name.nil? %> 
	<h3>Results for <%=link_to @name, 'http://www.google.com/search?q=' + @name, :target => '_blank' %></h3>
	<ul id="results">
		<% @response['results'].each do |el| %> 
			<li>
			<%=link_to image_tag(el['thumb']), 'http://www.discogs.com' + el['uri'], :target => "_blank" %> 
			<p><%= el['title'] %></br> 	
			<%= el['type'].titleize %></p>
			</li>
		<% end %> 
	<ul> 
<% end %> 

app/views/user/folders.html.erb
<div class="row">
  <div class="span12">
    <h1>Folders</h1>
    <% @data.each do |e| %> 
      <div><%= link_to e['name'], "folder/#{e['name']}" %></div>
    <% end %>
  </div>  
</div>